// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6ykvBKtbqmxHYlv-Cv0Cbf9FjxUe-xo',
    appId: '1:896579711958:android:f7c760b769a6dc5c5eea77',
    messagingSenderId: '896579711958',
    projectId: 'shop-2ca48',
    databaseURL: 'https://shop-2ca48-default-rtdb.firebaseio.com',
    storageBucket: 'shop-2ca48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7UuwBWbctpA-47JY824LJOJ72WFuCec',
    appId: '1:896579711958:ios:92a2ea73410214ea5eea77',
    messagingSenderId: '896579711958',
    projectId: 'shop-2ca48',
    databaseURL: 'https://shop-2ca48-default-rtdb.firebaseio.com',
    storageBucket: 'shop-2ca48.appspot.com',
    iosClientId: '896579711958-852croipg47loc19e8n46jqsoep6tfs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopApp',
  );
}
